<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: eallion
 * Date: Sat, 11 Mar 2017 01:45:49 +0800
 */

$conf['title'] = '蜗牛个人导航';
$conf['lang'] = 'zh';
$conf['template'] = 'stm';
$conf['tagline'] = '最简单最安全的网址导航，大大的小蜗牛的互联网入口。';
$conf['sidebar'] = '';
$conf['license'] = '';
$conf['breadcrumbs'] = 0;
$conf['showuseras'] = 'username';
$conf['deaccent'] = '2';
$conf['sneaky_index'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['htmlok'] = 1;
$conf['target']['interwiki'] = '_blank';
$conf['target']['extern'] = '_blank';
$conf['gzip_output'] = 1;
$conf['savedir'] = '/data/wwwroot/favorite.wiki/eallion/data';
$conf['tpl']['ipari-dokuwiki-template-white-cb74699']['numberedHeading'] = '1';
$conf['tpl']['wallpaper-master']['fixedbackground'] = '1';
$conf['tpl']['bootstrap3']['bootstrapTheme'] = 'bootswatch';
$conf['tpl']['bootstrap3']['bootswatchTheme'] = 'readable';
$conf['tpl']['bootstrap3']['hideInThemeSwitcher'] = 'cyborg,darkly,lumen,slate,superhero,yeti';
$conf['tpl']['bootstrap3']['showTranslation'] = '1';
$conf['tpl']['bootstrap3']['showTools'] = 'logged';
$conf['tpl']['bootstrap3']['showAdminMenu'] = '1';
$conf['tpl']['bootstrap3']['useLegacyNavbar'] = '1';
$conf['tpl']['bootstrap3']['fluidContainerBtn'] = '1';
$conf['tpl']['bootstrap3']['showPageId'] = '0';
$conf['tpl']['bootstrap3']['browserTitle'] = '蜗牛个人导航';
$conf['tpl']['bootstrap3']['showPageInfo'] = '0';
$conf['tpl']['bootstrap3']['pageIcons'] = 'social-share,help';
$conf['tpl']['bootstrap3']['socialShareProviders'] = 'facebook,google-plus,linkedin,pinterest,twitter';
$conf['tpl']['bootstrap3']['collapsibleSections'] = '1';
$conf['tpl']['vector']['vector_userpage'] = '0';
$conf['tpl']['vector']['vector_discuss'] = '0';
$conf['tpl']['vector']['vector_sitenotice_translate'] = '0';
$conf['tpl']['vector']['vector_navigation_translate'] = '0';
$conf['tpl']['vector']['vector_exportbox'] = '0';
$conf['tpl']['vector']['vector_exportbox_default'] = '0';
$conf['tpl']['vector']['vector_toolbox_default'] = '0';
$conf['tpl']['vector']['vector_qrcodebox'] = '0';
$conf['tpl']['vector']['vector_copyright_default'] = '0';
$conf['tpl']['vector']['vector_copyright_translate'] = '0';

// end auto-generated content
